"""
CNNTrainer — trains DASResNetClassifier with rich W&B logging.

Mirrors DOVE's logging pattern: per-class precision/recall/F1, confusion matrix,
ROC/PR curves, dataset distribution tables, results table, and prediction gallery
(DAS waterfall + softmax bar chart per sample).

Two runs are compared:
  baseline  — real DAS data only
  synthetic — real + synthetic data generated by the pixel-space diffusion model
"""

import os
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.amp import GradScaler, autocast
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm


class SyntheticDASDataset(Dataset):
    """In-memory dataset of synthetic DAS patches generated by the diffusion model.

    Each item: (patch [1, C, T] float32 tensor, class_idx int)
    Patches are in normalized (model) space — same scale as DASLatentPatchDataset.
    """

    def __init__(self, patches: List[torch.Tensor], labels: List[int]):
        self.patches = patches
        self.labels = labels

    def __len__(self) -> int:
        return len(self.patches)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        return self.patches[idx], self.labels[idx]


class BackgroundMixupDataset(Dataset):
    """Wraps a real event dataset and mixes each patch with a synthetic background.

    At every __getitem__ call:
        mixed = event_patch + alpha * bg_patch
    where bg_patch is drawn uniformly from bg_patches and alpha ~ Uniform(alpha_lo, alpha_hi).
    The class label is unchanged (it belongs to the event, not the background).

    Uses deterministic per-index RNG so augmentation is reproducible across epochs.
    """

    def __init__(
        self,
        base_dataset: Dataset,
        bg_patches: List[torch.Tensor],
        alpha_range: Tuple[float, float] = (0.0, 0.5),
        seed: int = 42,
    ):
        self.base = base_dataset
        self.bg_patches = bg_patches
        self.alpha_lo, self.alpha_hi = alpha_range
        self.seed = seed

    def __len__(self) -> int:
        return len(self.base)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        patch, label = self.base[idx]
        rng = np.random.default_rng(self.seed + idx)
        bg_idx = int(rng.integers(0, len(self.bg_patches)))
        alpha = float(rng.uniform(self.alpha_lo, self.alpha_hi))
        mixed = patch + alpha * self.bg_patches[bg_idx]
        return mixed, label


class CNNTrainer:
    def __init__(
        self,
        model: nn.Module,
        train_loader: DataLoader,
        val_loader: DataLoader,
        class_names: List[str],
        device: str,
        epochs: int,
        lr: float,
        weight_decay: float,
        grad_clip: float,
        amp: bool,
        scheduler_T0: int,
        checkpoint_dir: str,
        wandb_logger,
        log_every_n_epochs: int = 5,
        class_weights: Optional[torch.Tensor] = None,
        run_name: str = "cnn",
    ):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.class_names = class_names
        self.n_classes = len(class_names)
        self.device = device
        self.epochs = epochs
        self.grad_clip = grad_clip
        self.amp = amp
        self.checkpoint_dir = checkpoint_dir
        self.wb = wandb_logger
        self.run_name = run_name
        self.log_every_n_epochs = log_every_n_epochs

        w = class_weights.to(device) if class_weights is not None else None
        self.criterion = nn.CrossEntropyLoss(weight=w)

        self.optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
        self.scheduler = CosineAnnealingWarmRestarts(self.optimizer, T_0=scheduler_T0, T_mult=1)
        self.scaler = GradScaler("cuda", enabled=amp)

        self.noise_std = 0.0   # set via add_background_noise()
        self.best_val_f1 = -1.0
        os.makedirs(checkpoint_dir, exist_ok=True)

    def add_background_noise(self, std: float):
        """Add Gaussian background noise during training (normalized space)."""
        self.noise_std = float(std)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def fit(self):
        for epoch in range(self.epochs):
            train_m = self._train_epoch()
            val_m = self._validate()

            self._print_epoch(epoch, train_m, val_m)
            self._log_epoch(epoch, train_m, val_m)

            if (epoch + 1) % self.log_every_n_epochs == 0:
                self._log_periodic(epoch, val_m)

            self._save_checkpoint(epoch, val_m["loss"], val_m["f1_macro"])
            self.scheduler.step()

    # ------------------------------------------------------------------
    # Train / validate
    # ------------------------------------------------------------------

    def _train_epoch(self) -> Dict:
        self.model.train()
        losses, all_preds, all_targets = [], [], []

        for batch in tqdm(self.train_loader, leave=False, desc="train"):
            patch, class_idx = batch[0], batch[1]
            patch = patch.to(self.device)
            class_idx = self._to_long(class_idx)

            if self.noise_std > 0.0:
                patch = patch + torch.randn_like(patch) * self.noise_std

            self.optimizer.zero_grad()
            with autocast("cuda", enabled=self.amp):
                logits = self.model(patch)
                loss = self.criterion(logits, class_idx)

            self.scaler.scale(loss).backward()
            self.scaler.unscale_(self.optimizer)
            nn.utils.clip_grad_norm_(self.model.parameters(), self.grad_clip)
            self.scaler.step(self.optimizer)
            self.scaler.update()

            losses.append(loss.item())
            all_preds.extend(logits.argmax(1).cpu().tolist())
            all_targets.extend(class_idx.cpu().tolist())

        return self._compute_metrics(losses, all_preds, all_targets)

    def _validate(self) -> Dict:
        self.model.eval()
        losses, all_preds, all_targets, all_probs = [], [], [], []
        gallery_patches, gallery_preds, gallery_targets, gallery_probs = [], [], [], []
        n_gallery = 4

        with torch.no_grad():
            for batch in tqdm(self.val_loader, leave=False, desc="val"):
                patch, class_idx = batch[0], batch[1]
                patch = patch.to(self.device)
                class_idx = self._to_long(class_idx)

                with autocast("cuda", enabled=self.amp):
                    logits = self.model(patch)
                    loss = self.criterion(logits, class_idx)

                probs = F.softmax(logits, dim=1).cpu().numpy()
                preds = logits.argmax(1).cpu().tolist()
                targets = class_idx.cpu().tolist()

                losses.append(loss.item())
                all_probs.extend(probs.tolist())
                all_preds.extend(preds)
                all_targets.extend(targets)

                # Collect a handful of patches for the prediction gallery.
                if len(gallery_patches) < n_gallery:
                    remaining = n_gallery - len(gallery_patches)
                    b = min(remaining, patch.size(0))
                    gallery_patches.extend(patch[:b].cpu().numpy().tolist())
                    gallery_preds.extend(preds[:b])
                    gallery_targets.extend(targets[:b])
                    gallery_probs.extend(probs[:b].tolist())

        metrics = self._compute_metrics(losses, all_preds, all_targets)
        metrics.update({
            "all_preds": all_preds,
            "all_targets": all_targets,
            "all_probs": all_probs,
            "gallery_patches": gallery_patches,
            "gallery_preds": gallery_preds,
            "gallery_targets": gallery_targets,
            "gallery_probs": gallery_probs,
        })
        return metrics

    # ------------------------------------------------------------------
    # Metric computation
    # ------------------------------------------------------------------

    def _compute_metrics(self, losses: List[float], preds: List[int], targets: List[int]) -> Dict:
        from sklearn.metrics import accuracy_score, precision_recall_fscore_support

        labels = list(range(self.n_classes))
        prec, rec, f1, _ = precision_recall_fscore_support(
            targets, preds, labels=labels, average=None, zero_division=0
        )
        _, _, f1_mac, _ = precision_recall_fscore_support(
            targets, preds, labels=labels, average="macro", zero_division=0
        )
        return {
            "loss": float(np.mean(losses)),
            "acc": float(accuracy_score(targets, preds)),
            "precision": prec.tolist(),
            "recall": rec.tolist(),
            "f1": f1.tolist(),
            "f1_macro": float(f1_mac),
        }

    # ------------------------------------------------------------------
    # W&B logging — every epoch
    # ------------------------------------------------------------------

    def _log_epoch(self, epoch: int, train_m: Dict, val_m: Dict):
        if self.wb is None:
            return
        lr = self.optimizer.param_groups[0]["lr"]
        log = {
            "epoch": epoch + 1,
            "lr": lr,
            "train/loss": train_m["loss"],
            "train/acc": train_m["acc"],
            "train/f1_macro": train_m["f1_macro"],
            "val/loss": val_m["loss"],
            "val/acc": val_m["acc"],
            "val/f1_macro": val_m["f1_macro"],
        }
        for i, name in enumerate(self.class_names):
            for split, m in [("train", train_m), ("val", val_m)]:
                log[f"{split}/precision_{name}"] = m["precision"][i]
                log[f"{split}/recall_{name}"] = m["recall"][i]
                log[f"{split}/f1_{name}"] = m["f1"][i]

        # Dataset distribution (class counts in this epoch's targets)
        for split, m in [("train", train_m), ("val", val_m)]:
            if "all_targets" in m:
                counts = np.bincount(m["all_targets"], minlength=self.n_classes)
                table = self.wb.Table(columns=["class", "count"])
                for i, name in enumerate(self.class_names):
                    table.add_data(name, int(counts[i]))
                log[f"{split}/ds_distribution_table"] = table

        self.wb.log(log)

    # ------------------------------------------------------------------
    # W&B logging — periodic (every K epochs)
    # ------------------------------------------------------------------

    def _log_periodic(self, epoch: int, val_m: Dict):
        if self.wb is None:
            return

        log = {"epoch": epoch + 1}

        # Confusion matrix
        try:
            log["val/confusion_matrix"] = self.wb.plot.confusion_matrix(
                probs=val_m["all_probs"],
                y_true=val_m["all_targets"],
                class_names=self.class_names,
            )
        except Exception as e:
            print(f"  [W&B] confusion_matrix failed: {e}")

        # ROC and PR curves
        try:
            log["val/roc_curve"] = self.wb.plot.roc_curve(
                val_m["all_targets"], val_m["all_probs"], labels=self.class_names
            )
            log["val/pr_curve"] = self.wb.plot.pr_curve(
                val_m["all_targets"], val_m["all_probs"], labels=self.class_names
            )
        except Exception as e:
            print(f"  [W&B] ROC/PR curves failed: {e}")

        # Results table
        results_table = self.wb.Table(columns=["class", "precision", "recall", "f1"])
        for i, name in enumerate(self.class_names):
            results_table.add_data(
                name,
                round(val_m["precision"][i], 4),
                round(val_m["recall"][i], 4),
                round(val_m["f1"][i], 4),
            )
        log["val/results_table"] = results_table

        # Prediction gallery: 4 patches with waterfall + probability bars
        if val_m["gallery_patches"]:
            try:
                fig = self._make_gallery_figure(
                    val_m["gallery_patches"],
                    val_m["gallery_preds"],
                    val_m["gallery_targets"],
                    val_m["gallery_probs"],
                )
                log["val/prediction_gallery"] = self.wb.Image(fig)
                plt.close(fig)
            except Exception as e:
                print(f"  [W&B] prediction gallery failed: {e}")

        # Per-class samples: one patch per class, 8 per-channel spectrograms + logits
        try:
            fig = self._make_class_samples_figure()
            if fig is not None:
                log["val/heatmaps"] = self.wb.Image(fig)
                plt.close(fig)
        except Exception as e:
            print(f"  [W&B] class samples failed: {e}")

        self.wb.log(log)

    # ------------------------------------------------------------------
    # Prediction gallery figure
    # ------------------------------------------------------------------

    def _make_gallery_figure(
        self,
        patches: List,
        preds: List[int],
        targets: List[int],
        probs: List[List[float]],
    ) -> plt.Figure:
        n = len(patches)
        fig, axes = plt.subplots(
            2, n,
            figsize=(4 * n, 7),
            gridspec_kw={"height_ratios": [2, 1]},
        )
        if n == 1:
            axes = np.array(axes).reshape(2, 1)

        for i in range(n):
            patch = np.array(patches[i])          # [1, 8, T] or [8, T]
            patch_2d = patch[0] if patch.ndim == 3 else patch
            pred_idx = preds[i]
            true_idx = targets[i]
            prob = np.array(probs[i])

            # Row 0: waterfall
            ax_wf = axes[0, i]
            vmax = float(np.percentile(np.abs(patch_2d), 99)) or 1.0
            ax_wf.imshow(
                patch_2d, aspect="auto", cmap="seismic",
                vmin=-vmax, vmax=vmax, origin="lower",
            )
            color = "green" if pred_idx == true_idx else "red"
            ax_wf.set_title(
                f"True: {self.class_names[true_idx]}\nPred: {self.class_names[pred_idx]}",
                fontsize=9, color=color,
            )
            ax_wf.set_xticks([])
            ax_wf.set_yticks([])

            # Row 1: probability bar chart (logit probabilities)
            ax_bar = axes[1, i]
            bar_colors = [
                "forestgreen" if j == true_idx else "steelblue"
                for j in range(self.n_classes)
            ]
            ax_bar.barh(self.class_names, prob, color=bar_colors)
            ax_bar.set_xlim(0, 1.0)
            ax_bar.set_xlabel("probability", fontsize=8)
            ax_bar.tick_params(labelsize=8)
            for j, p in enumerate(prob):
                ax_bar.text(
                    min(p + 0.03, 0.92), j, f"{p:.2f}", va="center", fontsize=7
                )

        fig.tight_layout()
        return fig

    # ------------------------------------------------------------------
    # Per-class sample figure
    # ------------------------------------------------------------------

    def _make_class_samples_figure(self) -> Optional[plt.Figure]:
        """One patch per class from the val set.

        Layout: n_classes rows × (n_channels + 1) cols
          cols 0..C-1 : raw per-channel waveform (time-series)
          col C       : raw logits bar chart (model output before softmax)
        """
        self.model.eval()
        samples: dict = {}
        with torch.no_grad():
            for batch in self.val_loader:
                patch_b, class_idx_b = batch[0], batch[1]
                labels = self._to_long(class_idx_b).cpu().tolist()
                logits = self.model(patch_b.to(self.device))
                raw_logits = logits.cpu().numpy()
                for i, lbl in enumerate(labels):
                    if lbl not in samples:
                        samples[lbl] = {
                            "patch": patch_b[i, 0].numpy(),   # [8, T]
                            "logits": raw_logits[i],           # [n_classes]
                        }
                if len(samples) == self.n_classes:
                    break

        if not samples:
            return None

        C = next(iter(samples.values()))["patch"].shape[0]   # 8 channels
        n_rows = len(samples)
        n_cols = C + 1   # C waveforms + 1 logits bar

        fig, axes = plt.subplots(
            n_rows, n_cols,
            figsize=(2.0 * n_cols, 2.0 * n_rows),
            gridspec_kw={"width_ratios": [1] * C + [1.4]},
        )
        axes = np.array(axes).reshape(n_rows, n_cols)

        for row_i, cls_idx in enumerate(sorted(samples.keys())):
            patch_2d = samples[cls_idx]["patch"]   # [8, T]
            logits_i = samples[cls_idx]["logits"]  # [n_classes]
            pred_idx = int(np.argmax(logits_i))
            title_color = "green" if pred_idx == cls_idx else "red"

            for ch in range(C):
                ax = axes[row_i, ch]
                sig = patch_2d[ch]
                # Downsample for display if very long
                if sig.shape[0] > 2048:
                    step = sig.shape[0] // 2048
                    sig = sig[::step]
                ax.plot(sig, linewidth=0.4, color="steelblue")
                ax.set_xticks([])
                ax.set_yticks([])
                ax.margins(x=0)
                if ch == 0:
                    ax.set_ylabel(self.class_names[cls_idx], fontsize=8, color=title_color)
                if row_i == 0:
                    ax.set_title(f"ch{ch}", fontsize=7)

            # Raw logits bar chart
            ax_bar = axes[row_i, C]
            bar_colors = [
                "forestgreen" if j == cls_idx else "steelblue"
                for j in range(self.n_classes)
            ]
            ax_bar.barh(self.class_names, logits_i, color=bar_colors)
            for j, v in enumerate(logits_i):
                ax_bar.text(v + 0.05, j, f"{v:.2f}", va="center", fontsize=7)
            ax_bar.axvline(0, color="gray", linewidth=0.5)
            ax_bar.tick_params(labelsize=7)
            ax_bar.set_title(
                f"pred: {self.class_names[pred_idx]}",
                fontsize=7, color=title_color,
            )
            if row_i == 0:
                ax_bar.set_title("logits", fontsize=7)

        fig.suptitle("Val samples — per-channel waveform + logits", fontsize=9)
        fig.tight_layout()
        return fig

    # ------------------------------------------------------------------
    # Checkpoint
    # ------------------------------------------------------------------

    def _save_checkpoint(self, epoch: int, val_loss: float, val_f1: float):
        ckpt = {
            "epoch": epoch,
            "model_state": self.model.state_dict(),
            "optimizer_state": self.optimizer.state_dict(),
            "val_loss": val_loss,
            "val_f1_macro": val_f1,
        }
        last_path = os.path.join(self.checkpoint_dir, "cnn_last.pt")
        torch.save(ckpt, last_path)
        if val_f1 > self.best_val_f1:
            self.best_val_f1 = val_f1
            best_path = os.path.join(self.checkpoint_dir, "cnn_best.pt")
            torch.save(ckpt, best_path)
            print(f"  * new best f1={val_f1:.4f} (epoch {epoch + 1})")
            if self.wb is not None:
                artifact = self.wb.Artifact(
                    name=f"cnn_best_{self.run_name}",
                    type="model",
                    metadata={"epoch": epoch + 1, "val_loss": round(val_loss, 6), "val_f1_macro": round(val_f1, 6)},
                )
                artifact.add_file(best_path)
                self.wb.log_artifact(artifact)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _to_long(self, class_idx) -> torch.Tensor:
        if isinstance(class_idx, torch.Tensor):
            return class_idx.long().to(self.device)
        return torch.tensor(class_idx, dtype=torch.long, device=self.device)

    @staticmethod
    def _print_epoch(epoch: int, train_m: Dict, val_m: Dict):
        print(
            f"Epoch {epoch + 1:3d} | "
            f"train loss={train_m['loss']:.4f} acc={train_m['acc']:.3f} f1={train_m['f1_macro']:.3f} | "
            f"val   loss={val_m['loss']:.4f} acc={val_m['acc']:.3f} f1={val_m['f1_macro']:.3f}"
        )
