"""
Shared recording-level dataset split for all DAS training scripts.

Both the diffusion model and the CNN classifier must use the same split so
that synthetic patches generated by the diffusion model come exclusively from
recordings seen during diffusion training — not from CNN validation recordings.
"""

from collections import defaultdict
from typing import Tuple

import numpy as np
from torch.utils.data import Dataset, Subset


def recording_level_split(
    dataset: Dataset,
    val_frac: float,
    test_frac: float,
    seed: int,
) -> Tuple[Subset, Subset, Subset]:
    """Stratified recording-level split.

    Classes with >= 2 recordings: split by recording file (zero patch-level leakage).
    Classes with 1 recording:     temporal split by win_idx (earlier = train, later = val/test).

    Returns (train_subset, val_subset, test_subset).
    """
    class_rec_to_patches: dict = defaultdict(lambda: defaultdict(list))
    for i, (cache_path, win_idx, _, class_idx) in enumerate(dataset.samples):
        class_rec_to_patches[class_idx][cache_path].append((win_idx, i))

    train_idx, val_idx, test_idx = [], [], []
    rng = np.random.default_rng(seed)
    summary = []

    for class_idx in sorted(class_rec_to_patches.keys()):
        recs = sorted(class_rec_to_patches[class_idx].keys())
        n = len(recs)

        if n >= 3:
            # Enough recordings for a pure recording-level split.
            rng.shuffle(recs)
            n_val_r  = max(1, int(n * val_frac))
            n_test_r = max(1, int(n * test_frac))
            n_train_r = n - n_val_r - n_test_r

            for r in recs[:n_train_r]:
                train_idx.extend(i for _, i in class_rec_to_patches[class_idx][r])
            for r in recs[n_train_r:n_train_r + n_val_r]:
                val_idx.extend(i for _, i in class_rec_to_patches[class_idx][r])
            for r in recs[n_train_r + n_val_r:n_train_r + n_val_r + n_test_r]:
                test_idx.extend(i for _, i in class_rec_to_patches[class_idx][r])

            summary.append(
                f"    class {class_idx}: {n} recs (recording-split) -> "
                f"{n_train_r} train / {n_val_r} val / {n_test_r} test recs"
            )
        elif n == 2:
            # 1 recording for train; temporally split the other into val + test.
            rng.shuffle(recs)
            train_idx.extend(i for _, i in class_rec_to_patches[class_idx][recs[0]])
            holdout = sorted(class_rec_to_patches[class_idx][recs[1]], key=lambda x: x[0])
            n_h = len(holdout)
            # Split holdout 50/50 between val and test (both sets get equal coverage).
            n_val_h = n_h // 2
            val_idx.extend(i for _, i in holdout[:n_val_h])
            test_idx.extend(i for _, i in holdout[n_val_h:])

            summary.append(
                f"    class {class_idx}: 2 recs -> 1 train rec + "
                f"1 rec temporal-split ({n_val_h} val / {n_h - n_val_h} test patches)"
            )
        else:
            # Single recording — temporal split by win_idx.
            rec = recs[0]
            patches_sorted = sorted(class_rec_to_patches[class_idx][rec], key=lambda x: x[0])
            n_p = len(patches_sorted)
            n_val_p  = max(1, int(n_p * val_frac))
            n_test_p = max(1, int(n_p * test_frac))
            n_train_p = n_p - n_val_p - n_test_p

            train_idx.extend(i for _, i in patches_sorted[:n_train_p])
            val_idx.extend(i for _, i in patches_sorted[n_train_p:n_train_p + n_val_p])
            test_idx.extend(i for _, i in patches_sorted[n_train_p + n_val_p:n_train_p + n_val_p + n_test_p])

            summary.append(
                f"    class {class_idx}: 1 rec (temporal-split) -> "
                f"{n_train_p} train / {n_val_p} val / {n_test_p} test patches"
            )

    print("  Recording-level split (stratified per class):")
    for s in summary:
        print(s)
    print(
        f"  Total patches -> train:{len(train_idx)}  "
        f"val:{len(val_idx)}  test:{len(test_idx)}"
    )
    return (
        Subset(dataset, train_idx),
        Subset(dataset, val_idx),
        Subset(dataset, test_idx),
    )
